### ISSUE TITLE
Define historical aerial photos metadata

### ISSUE THREAD

**Issue by dwsilk** [linz/topo-processor#31]
### User Story

In order to collate metadata for each image with the images as a dev I want a defined list of historical aerial photos metadata.

#### Acceptance Criteria
- [x] Metadata field list with brief definitions
- [x] Some examples / samples of what the field actually looks like
- [x] Comments as to usefulness for the public / commonly empty

**Comment by palmerj** [comment]
Nice. Would be also good to line this up against https://confluence.linz.govt.nz/display/LGDL/Data+Lake+Metadata+Requirements and suggest changes if required.

**Comment by SLMcColley** [comment]
[Historical Imagery database columns.docx](https://github.com/linz/topo-processor/files/5352326/Historical.Imagery.database.columns.docx)

**Comment by Ben-Cheng** [comment]
I have put the above doc on confluence [here](https://confluence.linz.govt.nz/display/GEOD/Database+Fields).
