### ISSUE TITLE
Learn more about STAC and json-schema

### ISSUE THREAD

**Issue by dwsilk** [linz/topo-processor#32]
### User Story

In order to consistently collate metadata for each image to an international standard as a dev I want to understand how historical aerial photo metadata could be represented in a STAC file.

#### Acceptance Criteria
- [x] https://stacspec.org/
- [ ] https://github.com/radiantearth/stac-spec/blob/master/best-practices.md
- [ ] https://json-schema.org/learn/
- [x] Basemaps example: https://github.com/linz/basemaps/blob/master/packages/landing/static/json-schema/stac-basemaps-extension/1.0/schema.json
- [x] https://github.com/radiantearth/stac-spec/tree/master/extensions

**Comment by MDavidson17** [comment]
done preliminary investigations.
