### ISSUE TITLE
Create List of Files and File Sizes of Historical Imagery

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#39]
As a Blayne I need to provide cost estimations for data storage of historical imagery to management in order to fund the short term backup of historic imagery.

- [x] csv/txt file listing
- [x] file name : file size (bytes)

nb: can use linux machine to run script on hard drives

**Comment by blacha** [comment]
Here is a simple bash script that will create a TSV from a linux system.

```
shopt -s globstar dotglob nullglob

for pathname in ./**/*; do
    if [[ -f $pathname ]] && [[ ! -h $pathname ]]; then
        stat -c $'%s\t%n' "$pathname"
    fi
done >outfile.csv
```

from https://unix.stackexchange.com/questions/560351/save-in-a-text-file-list-of-files-with-the-size-of-each-file
