### ISSUE TITLE
Create Physical Board

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#40]
As a LDA I want a physical board to act as an information radiator of our tasks

- [x] make grids
- [x] label the boxes
- [x] make all the faces on magnets

**Comment by Ben-Cheng** [comment]
@linzbjones has ordered some more tapes..

**Comment by Ben-Cheng** [comment]
Shannon's pic:

![49864408_10157148529177033_753259322946879488_o](https://user-images.githubusercontent.com/42329567/96921509-208f0700-150b-11eb-9b37-943922049397.jpg)

**Comment by Ben-Cheng** [comment]
![image](https://user-images.githubusercontent.com/42329567/97504231-5b95ac80-19db-11eb-9125-edbf0d517605.jpeg)
