### ISSUE TITLE
Make 'Create STAC Metadata script'

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#43]
### User Story
As a Dev I want a script that takes a tiff historical imagery file and creates a STAC metadata output for it in order to create machine-readable metadata for historical imagery files. 

### Acceptance Criteria
create a function that:
- [ ] takes a tiff file path as an input
- [ ] returns stac metadata json object 
- [ ] use logging
- [ ] Adheres to https://confluence.linz.govt.nz/display/LGDL/Data+Lake+Metadata+Requirements

nb: Use [data lake](https://github.com/linz/linz-data-lake/tree/13de68799f66d5b006ca2a387ba42f1db3e5bc65) as an example

**Comment by Ben-Cheng** [comment]
done
