### ISSUE TITLE
Create project background documentation

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#45]
### User Story
As a LINZ employee, I want to know about this new project, I would  like documentation explaining 

- What this project is about/why it is important
- What it's goals are
- What does "Done" look like
- How the system is put together

#### Acceptance Criteria

- [x] Background documentation created
- [ ] System documentation created
- [ ] Team has reviewed documentation.
- [ ] diagrams

#### Assumption

Documentation to be created in confluence

**Comment by blacha** [comment]
Background documentation https://confluence.linz.govt.nz/display/TOP/Topo+Processor+background

**Comment by MDavidson17** [comment]
Done for now
