### ISSUE TITLE
Create Working Agreement

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#51]
### User Story

In order to work cohesively as a team as a dev, I want a working agreement for the Topo Data Engineering Agile Squad

#### Acceptance Criteria
- [x] Written In confluence
- [x] Links to pages Blayne Demoed
- [x] Github is source of truth for issue tracking
- [x] sprint ceremony times and days
- [x] sprint naming guidelines
- [ ] etc

**Comment by Ben-Cheng** [comment]
https://confluence.linz.govt.nz/display/GEOD/Working+Agreement
