### ISSUE TITLE
Align LINZ's STAC Metadata extensions

### ISSUE THREAD

**Issue by blacha** [linz/topo-processor#56]
### User Story
As a User I want to have standardised ways of using STAC metadata across LINZ's products

#### Acceptance Criteria
- [x] Review Basemaps metadata extensions
- [x] Review Datalake metadata extensions
- [x] Propose a way to align the metadata extensions across the projects

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by blacha** [comment]
@palmerj  Said this as part of a pull request comment #55 
> I think we should try to use as many of the built in STAC fields as possible. e.g linz:date -> STAC item:created, Linz:camera -> STAC item:instruments. Also, rather than just packing everything into a "linz" extension, we could consider creating an Aerial Photography extension for certain field. Maybe some ideas could be taken from USGS https://lta.cr.usgs.gov/DD/nhap.html#frame. But some better searching might also be worth while.

**Comment by blacha** [comment]
I just found this, which looks to be a interesting way of mapping existing metadata to some stac extensions

https://github.com/stac-utils/stac-crosswalks

**Comment by palmerj** [comment]
Does look interesting. Pity ISO 19115 hasn't been done yet. But likely not too hard to do. For our LINZ metadata project that we are talking about in the S&I programme I think we really need to be considering how we are store our metadata and then map to other formats such as ISO 19115/19139

**Comment by Ben-Cheng** [comment]
Datalake metadata extensions:
```
    properties = {
        "created": d.isoformat("T") + "Z",
        "proj:epsg": int(layer.srs.GetAuthorityCode(None)),
        "eo:gsd": round(layer.resolution[0], 3),
        "eo:bands": [b.to_dict() for b in bands],
        "start_datetime": metadata["start_datetime"].isoformat("T", timespec="milliseconds") + "Z",
        "end_datetime": metadata["end_datetime"].isoformat("T", timespec="milliseconds") + "Z",
        "datetime": metadata["datetime"].isoformat("T", timespec="milliseconds") + "Z",
    }
```

**Comment by Ben-Cheng** [comment]
Basemap metadata extensions:
```
        properties: {
            datetime: created,
            'checksum:multihash': await Hash.hash(outputTiffPath),
            'proj:epsg': tms.projection.code,
            'linz:gdal:version': await bm.gdalVersion,
        },
```

**Comment by Ben-Cheng** [comment]
Mapping Database Fields to STAC Specification:
https://confluence.linz.govt.nz/display/TOP/Mapping+Database+Fields+to+STAC+Specification

LINZ Common Practice for STAC:
https://confluence.linz.govt.nz/display/TOP/LINZ+Common+Practice+for+STAC#LINZCommonPracticeforSTAC-summariesmap
