### ISSUE TITLE
Compare LINZ Lidar Metadata to STAC extension

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#65]
### User Story

In order to prepare for uploading LiDAR data as an LDA I want to gather metadata requirements.

#### Acceptance Criteria
- [x] create confluence page for STAC mapping
- [ ] make the page similar to [this](https://confluence.linz.govt.nz/display/TOP/Mapping+Database+Fields+to+STAC+Specification) but for PGF lidar metadata
- [ ] liaise with SME (Rose) to find out metadata there is

**Comment by Ben-Cheng** [comment]
To arrange a meeting with @rphillips91 next week.

**Comment by rphillips91** [comment]
- [ ] Review and prepare summary of LAS file structures and terminology 
- [ ] Book meeting with @MDavidson17 @Ben-Cheng 
- [ ] Discuss metadata
