### ISSUE TITLE
Extract more metadata from Tiffs

### ISSUE THREAD

**Issue by MDavidson17** [linz/topo-processor#66]
### User Story

In order to improve metadata as an LDA I want to extract more information from the tiff files 

#### Acceptance Criteria
- [x] use rasterio to get more info about the tiff
- [x] list tags made in files (historical image)
- [ ] has a pattern to validate info from tiff to check against the properties in stac metadata: e.g. imagery_type
- [x] add test data

**Comment by MDavidson17** [comment]
### Options:
**PIL: https://pillow.readthedocs.io/en/stable/installation.html**
 https://github.com/python-pillow
- maybe not that well maintained? 
- cannot co-exist with pillow
- hydro has used it?
- smaller than GDAL

**GDAL: https://gdal.org/**
- large (maybe we can only install the raster part?)
- widely used
- better maintained

**Exifread: https://pypi.org/project/ExifRead/**
- small 
- recent updates

**tifffile: https://pypi.org/project/tifffile/**
- lesser known
- smaller than GDAL larger than the others

**Comment by Ben-Cheng** [comment]
We will use GDAL because it is licensed under an MIT/X style license.
It is open source
It has a lot of github activities
It has a big community

**Comment by MDavidson17** [comment]
Going to use: https://pypi.org/project/aiocogeo/
Need to investigate async/await
