### ISSUE TITLE
Investigate how to write a json schema

### ISSUE THREAD

**Issue by Ben-Cheng** [linz/topo-processor#88]
### User Story
Lean how to write a json schema because we need it in STAC and we see it often.

#### Acceptance Criteria
- [x] learnt how to write a json schema
- [x] documented on confluence
- [x] be able to demo to the rest of the team

- [x] explain how to use json schema to validate - AJV Cli
- [x] how to use json schema for type checking in vs code

**Comment by MDavidson17** [comment]
https://confluence.linz.govt.nz/display/TOP/JSON+Schema
