### ISSUE TITLE
Investigate AWS permissions

### ISSUE THREAD

**Issue by Ben-Cheng** [linz/topo-processor#92]
### User Story

In order to manage all access with AWS as a LDA I want to investigate AWS permissions

#### Acceptance Criteria
- [ ] investigated AWS permissions
- [ ] created a new confluence page
- [ ] documented in confluence and be able to demo to the rest of the team

**Comment by MDavidson17** [comment]
https://confluence.linz.govt.nz/display/TOP/AWS+Permissions+WIP
